# See the documentation for more information:
# https://packit.dev/docs/configuration/

---
srpm_build_deps:
  - tito

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - epel-8-x86_64
        - epel-9-x86_64
        - fedora-all-x86_64
    actions:
      create-archive:
        - bash -c "tito build --tgz --test -o ."
        - bash -c "ls -1t *.tar.gz | head -n 1"
      get-current-version:
        - bash -c "git describe --tags --match vcs-diff-lint-[0-9]* --abbrev=0 HEAD | egrep -o [0-9]+\.[0-9]+"
    specfile_path: vcs-diff-lint.spec
    upstream_package_name: vcs-diff-lint
    downstream_package_name: vcs-diff-lint
    upstream_tag_template: 'vcs-diff-lint-{version}'

  - <<: *copr
    trigger: commit
    metadata:
      owner: "@copr"
      project: "vcs-diff-lint"
      branch: main
